---
keys:
  - &scotte age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
  - &hera age1y5775nrh792zh2z4c8xpxf432e5xdwj03g4lgvcuv69zrzk0ju0qfruczz
  - &nixvm age12cwljj0azxcsre5kmf8hpmvt9m9lszmpwhp08794c5wd78ckne3qhh89cz
  - &ragnar age159dryl0uvkx3pjr0n36lf3cx0wqx96a4dpjgxmezpc8tlzppas0sdazq5h
  - &titan age1lua3t6kcp6wp2925uqt4td89n46dxg2qh5ngfj90cpahc52pgqdsdmlg89

creation_rules:
  - path_regex: .*\.sops\.yaml$
    key_groups:
      - age:
          - *scotte
          - *hera
          - *nixvm
          - *ragnar
          - *titan
  - path_regex: .*\.sops\.env
    key_groups:
      - age:
          - *scotte
