---
keys:
  - &scotte age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
  - &hera age1y6dd6qpn5ez37dthj6cut8dqku5wlhnwjuhjclm5m4wd3n79rc2qnpdwds
  - &nixvm age1n535v3x2yt26j6vfg4n8sxlrf5thm6rnqqcy3aew09cm2m5gmukqyjj0n0
  - &ragnar age159dryl0uvkx3pjr0n36lf3cx0wqx96a4dpjgxmezpc8tlzppas0sdazq5h
  - &titan age1pmlxqpau22yhfqga77ctpugmf4uagpedz6x8jspdmeam6h46dp7s4ts23q

creation_rules:
  - path_regex: .*\.sops\.yaml$
    key_groups:
      - age:
          - *scotte
          - *hera
          - *nixvm
          - *ragnar
          - *titan
  - path_regex: .*\.sops\.env
    key_groups:
      - age:
          - *scotte
