---
version: "3"

includes:
  nix:
    taskfile: ".taskfiles/nix"
    dir: "{{.ROOT_DIR}}"
  pc:
    taskfile: ".taskfiles/pre-commit"
    dir: "{{.ROOT_DIR}}"
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops

tasks:
  default:
    silent: true
    cmds:
      - task -l

  bootstrap:
    desc: Bootstrap installation
    cmds:
      - task: fix-git
      - task: pc:init
      - task: fetch-secrets

  fix-git:
    desc: Set the git remote URL to be used via ssh
    silent: true
    cmds:
      - git remote set-url origin git@github.com:szinn/nix-config.git

  fetch-secrets:
    desc: Fetch secrets from 1P
    cmd: ./scripts/fetch-secrets

  lint:
    desc: Run statix lint
    cmds:
      - statix check .

  check:
    desc: Check project files
    cmds:
      - task: lint
      - task: pc:run
