---
version: "3"

includes:
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops

tasks:
  default:
    silent: true
    cmds:
      - task -l

  bootstrap:
    desc: Bootstrap installation
    cmds:
      - task: fix-git
      - task: pc-init
      - task: fetch-secrets

  update:
    desc: Update flake
    cmd: nix flake update

  fix-git:
    desc: Set the git remote URL to be used via ssh
    silent: true
    cmds:
      - git remote set-url origin git@github.com:szinn/nix-config.git

  pc-init:
    desc: Initialize pre-commit hooks
    cmds:
      - pre-commit install --install-hooks

  pc-update:
    desc: Update pre-commit dependencies
    cmds:
      - pre-commit autoupdate

  pc-run:
    desc: Run pre-commit
    cmds:
      - pre-commit run --all-files

  fetch-secrets:
    desc: Fetch secrets from 1P
    cmd: ./scripts/fetch-secrets

  gc:
    desc: Garbage collect Nix
    cmds:
      - home-manager expire-generations "-3 days"
      - nix-store --gc

  lint:
    desc: Run statix lint
    cmds:
      - statix check .

  check:
    desc: Check project files
    cmds:
      - task: lint
      - task: pc-run

  create-titan:
    desc: Create titan VM
    cmds:
      - prlctl create titan -o other
      - prlctl set titan --device-set cdrom0 --image ~/Downloads/nixos-minimal-23.11.6621.dd37924974b9-aarch64-linux.iso  --connect
      - prlctl set titan --device-set net0 --type bridged
      - prlctl set titan --device-set net0 --mac DECAFF20001F
      - prlctl set titan --memsize 16384
      - prlctl set titan --cpus 4
      - prlctl set titan --device-set hdd0 --size 128G
      - prlctl start titan

  destroy-titan:
    desc: Destroy titan VM
    cmds:
      - prlctl stop titan --kill
      - prlctl delete titan

  get-titan-config:
    desc: Fetch titan configuration
    cmds:
      - scp hosts/titan/configuration.nix root@titan:/mnt/etc/nixos/configuration.nix
      - scp root@titan:/mnt/etc/nixos/hardware-configuration.nix hosts/titan/hardware-configuration.nix
