---
version: "3"

includes:
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops

tasks:
  default:
    silent: true
    cmds:
      - task -l

  bootstrap:
    desc: Bootstrap installation
    cmds:
      - task: fix-git
      - task: pc-init
      - task: fetch-secrets

  update:
    desc: Update flake
    cmd: nix flake update

  fix-git:
    desc: Set the git remote URL to be used via ssh
    silent: true
    cmds:
      - git remote set-url origin git@github.com:szinn/nix-config.git

  pc-init:
    desc: Initialize pre-commit hooks
    cmds:
      - pre-commit install --install-hooks

  pc-update:
    desc: Update pre-commit dependencies
    cmds:
      - pre-commit autoupdate

  pc-run:
    desc: Run pre-commit
    cmds:
      - pre-commit run --all-files

  fetch-secrets:
    desc: Fetch secrets from 1P
    cmd: ./scripts/fetch-secrets

  gc:
    desc: Garbage collect Nix
    cmds:
      - home-manager expire-generations "-3 days"
      - nix-store --gc

  lint:
    desc: Run statix lint
    cmds:
      - statix check .

  check:
    desc: Check project files
    cmds:
      - task: lint
      - task: pc-run

  host-configure:
    desc: Configure a host
    cmds:
      - ssh-copy-id -f -i ~/.ssh/id_ed25519.pub root@{{.host}}
      - scp ./hosts/titan/disks.sh root@{{.host}}:/root/disks.sh
      - ssh root@{{.host}} "/root/disks.sh"
      - task: get-key
        vars:
          host: "{{.host}}"
    requires:
      vars:
        - host

  host-install:
    desc: Install on the host
    cmds:
      - ssh root@{{.host}} "nix-shell -p git --run 'nixos-install --impure --flake github:szinn/nix-config#titan'"
    requires:
      vars:
        - host

  finalize-install:
    desc: Run final installation steps
    cmd: ./scripts/finalize-install

  create-titan:
    desc: Create titan VM
    cmds:
      - prlctl create titan -o other
      - prlctl set titan --device-set cdrom0 --image ~/Downloads/nixos-minimal-23.11.6621.dd37924974b9-aarch64-linux.iso  --connect
      - prlctl set titan --device-set net0 --type bridged
      - prlctl set titan --device-set net0 --mac DECAFF20001F
      - prlctl set titan --memsize 16384
      - prlctl set titan --cpus 4
      - prlctl set titan --device-set hdd0 --size 128G
      - prlctl start titan

  destroy-titan:
    desc: Destroy titan VM
    cmds:
      - prlctl stop titan --kill
      - prlctl delete titan

  get-titan-config:
    desc: Fetch titan configuration
    cmds:
      - scp hosts/titan/configuration.nix root@10.0.0.7:/mnt/etc/nixos/configuration.nix
      - scp root@10.0.0.7:/mnt/etc/nixos/hardware-configuration.nix hosts/titan/hardware-configuration.nix

  get-hera-config:
    desc: Fetch titan configuration
    cmds:
      - scp hosts/hera/configuration.nix root@hera.zinn.tech:/mnt/etc/nixos/configuration.nix
      - scp root@hera.zinn.tech:/mnt/etc/nixos/hardware-configuration.nix hosts/hera/hardware-configuration.nix
      - sops -d homes/scotte/hosts/hera/secrets.sops.yaml | sed 's/scotte-password:\ //' > /tmp/password_hash
      - scp /tmp/password_hash root@hera.zinn.tech:/mnt/persist/etc/users/scotte
      - rm /tmp/password_hash

  get-key:
    desc: Get ssh key for sops
    cmds:
      - scp root@{{.host}}:/mnt/etc/ssh/ssh_host_ed25519_key.pub /tmp/ssh_host_ed25519_key.pub
      # - scp root@{{.host}}:/mnt/persist/etc/ssh/ssh_host_ed25519_key.pub /tmp/ssh_host_ed25519_key.pub
      - ssh-to-age < /tmp/ssh_host_ed25519_key.pub
      - rm /tmp/ssh_host_ed25519_key.pub
    requires:
      vars:
        - host

  deploy-nixos:
    desc: Build and deploy nixos configuration using deploy-rs
    silent: true
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - deploy "{{.ROOT_DIR}}/#{{.host}}" --interactive --skip-checks
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which deploy
        msg: "deploy-rs not found"
