#!/usr/bin/env bash
HOSTNAME=$(hostname -s)

function listSecrets() {
  op item list --tags $HOSTNAME
}

function fetchAllSecrets() {
  secrets=$(op item list --tags $HOSTNAME | sed 1,1d | awk '{print $1}')
  for id in $secrets; do
    fetchSecret $id
  done
}

function fetchSecret() {
  id=$1
  info=$(op item get $id --format json)
  title=$(echo $info | jq -r .title)
  filename=$(echo $info | jq -r .files[0].name)
  path=$(op item get $id --fields label=$HOSTNAME:path --format json | jq -r .value)
  echo Processing $title
  mkdir -p $path
  op document get $id --out-file $path/$filename > /dev/null
  script=$(op item get $id --fields label=$HOSTNAME:script --format json | jq -r .value)
  if [[ -n $script ]]; then
    op item get $id --fields label=$HOSTNAME:script --format json | jq -r .value > script
    source ./script
    rm script
  fi
}

case $1 in
  all)
    fetchAllSecrets
    ;;
  list)
    listSecrets
    ;;
  *)
    if [[ -z $1 ]]; then
      fetchAllSecrets
    else
      fetchSecret $1
    fi
    ;;
esac
