# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.

{ pkgs }:

let
  vscode-utils = pkgs.vscode-utils;
in
{
  "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "prettier-vscode";
    publisher = "esbenp";
    version = "10.1.0";
    sha256 = "01s0vi2h917mqfpdrhqhp2ijwkibw95yk2js0l587wvajbbry2s9";
  };
}
