---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Nix Systems

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - "**.nix"
      - "flake.lock"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  nix-build:
    if: github.event.pull_request.draft == false
    permissions:
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: odin
            os: macos-14
          # - system: hera
          #   os: ubuntu-latest
          - system: ragnar
            os: ubuntu-latest
          - system: titan
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create nix mount point
        if: contains(matrix.os, 'ubuntu')
        run: sudo mkdir /nix

      - name: Maximize build space
        uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # v10
        if: contains(matrix.os, 'ubuntu')
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          build-mount-path: "/nix"
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-docker-images: true
          remove-codeql: true
          overprovision-lvm: true

      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          extra_nix_config: |
            auto-optimise-store = true
            system-features = nixos-test benchmark big-parallel kvm
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          name: szinn
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Garbage collect build dependencies
        run: nix-collect-garbage

      - name: Build previous ${{ matrix.system }} system
        if: github.event_name == 'pull_request'
        run: |
          nix build \
            "github:szinn/nix-config#ciSystems.${{ matrix.system }}" \
            -v \
            --log-format raw \
            --profile ./profile

      - name: Build new ${{ matrix.system }} system
        run: |
          set -o pipefail
          nix build \
            ".#ciSystems.${{ matrix.system }}" \
            --profile ./profile \
            --fallback \
            -v \
            --log-format raw > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2)

      - name: Output build failure
        if: failure()
        run: |
          drv=$(grep "For full logs, run" /tmp/nix-build-err.log | grep -oE "/nix/store/.*.drv")
          if [ -n $drv ]; then
            nix log $drv
            echo $drv
          fi
          exit 1

      - name: Diff profile
        if: github.event_name == 'pull_request'
        id: diff
        run: |
          nix profile diff-closures --profile ./profile
          delimiter="$(openssl rand -hex 16)"
          echo "diff<<${delimiter}" >> "${GITHUB_OUTPUT}"
          nix profile diff-closures --profile ./profile | perl -pe 's/\e\[[0-9;]*m(?:\e\[K)?//g' >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Comment report in pr
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: ".#ciSystems.${{ matrix.system }}"
          message: |
            ### Report for `${{ matrix.system }}`

            <summary> Version changes </summary> <br>
            <pre> ${{ steps.diff.outputs.diff }} </pre>

  nix-build-success:
    if: ${{ always() }}
    needs:
      - nix-build
    name: Nix Build Successful
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        name: Check matrix status
        run: exit 1
