name: Update nvfetcher

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: 0 * * * *
  push:
    branches:
      - main
    paths:
      - pkgs/nvfetcher.toml

jobs:
  update-nvfetcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9

      - name: Run nvfetcher
        id: run-nvfetcher
        run: |
          cd pkgs
          nix-shell -p nvfetcher --command 'nvfetcher -l /tmp/nvfetcher-changes'
          {
            echo 'changes<<EOF'
            cat /tmp/nvfetcher-changes
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Update vendor hashes
        id: update-vendorhash
        run: |
          setHash () {
            jq --arg app "${1}" --arg hash "${2}" '.[$app] = $hash' pkgs/_sources/vendorhash.json > tmp.json
            mv tmp.json pkgs/_sources/vendorhash.json
          }

          declare -a APP_NAMES
          while read line; do
            APP_NAMES+=("${line%:*}")
          done < /tmp/nvfetcher-changes

          for APP_NAME in "${APP_NAMES[@]}"; do
            echo "Updating vendor hash for ${APP_NAME}..."
            setHash "${APP_NAME}" ""
            vendorHash=$(nix build --no-link .#${APP_NAME} 2>&1 >/dev/null | grep "got:" | cut -d':' -f2 | sed 's| ||g')

            if [[ -n "${vendorHash}" ]]; then
              setHash "${APP_NAME}" "${vendorHash}"
              echo "Updated ${APP_NAME} with vendorHash: ${vendorHash}"
            fi
          done

      - name: Generate Token
        uses: actions/create-github-app-token@136412a57a7081aa63c935a2cc2918f76c34f514 # v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: nvfetcher/deps
          title: "chore(deps): Update packages managed by nvfetcher"
          commit-message: "chore(deps): Update packages managed by nvfetcher"
          body: |
            ## Changes:
            ${{ steps.run-nvfetcher.outputs.changes }}
          add-paths: |
            pkgs/**
          delete-branch: true
